---
  - name: install wget
    yum: name=wget state=latest

  - name: download oracle JDK 8
    get_url: url=http://download.oracle.com/otn-pub/java/jdk/8u102-b14/jdk-8u102-linux-x64.rpm dest=/tmp/jdk-8u102-linux-x64.rpm headers="Cookie:' gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'" validate_certs=no owner=root group=root mode=744

  - name: install oracle JDK 8
    yum: name=/tmp/jdk-8u102-linux-x64.rpm state=present
