---

- name: Download Jenkins war
  get_url:
    url="http://mirrors.jenkins-ci.org/war-stable/latest/jenkins.war"
    dest={{ jetty_dst_dir }}/jetty/webapps/

- name: Change owner Jenkins
  command: "chown -R {{ jetty_user_login }}:{{ jetty_group_name }} {{ jetty_dst_dir }}/jetty/webapps/jenkins.war"

- name: Jenkins
  template:
    src=roles/cmg/jetty/templates/jenkins.j2
    dest={{ jetty_dst_dir }}/jetty/webapps/jenkins.xml
    owner={{ jetty_user_login }}
    group={{ jetty_group_name }}
